### DISCUSSION TITLE
🎨 shadcn/uiのセットアップ

### DISCUSSION THREAD

**Discussion by kagomen** [lgtm-factory/lgtm-factory#111] [Scrap]
#107 こちらで設定した項目について記録
以下に沿ってやっていく
https://ui.shadcn.com/docs/installation/next

**Comment by kagomen** [comment]
```
npx shadcn-ui@latest init

✔ Which style would you like to use? › Default
✔ Which color would you like to use as base color? › Zinc
✔ Would you like to use CSS variables for colors? … yes
```

以下が作成される
- lib/utils.ts
- components.json

以下が編集される
- package.json
- app/globals.css

---

`Would you like to use CSS variables for colors?` に "Yes" と答えると、以下のような効果があります：

1. カラーシステムの柔軟性:
   - カラーがCSS変数として定義されるため、テーマの変更やカスタマイズが容易になります。

2. 動的なテーマ切り替え:
   - JavaScriptを使用してCSS変数を変更することで、ダークモードなどの動的なテーマ切り替えが簡単に実装できます。

3. コンポーネントのスタイリング:
   - コンポーネント内でこれらのCSS変数を参照することで、一貫性のあるカラースキームを維持しやすくなります。

4. グローバルなカラー管理:
   - プロジェクト全体で統一されたカラーパレットを使用できます。

5. パフォーマンス:
   - CSS変数はブラウザネイティブでサポートされているため、効率的です。

6. 開発者体験の向上:
   - カラーの調整や実験が容易になり、デザインシステムの構築と維持が簡単になります。

例えば、以下のようなCSS変数が定義されます：

```css
:root {
  --background: 0 0% 100%;
  --foreground: 222.2 47.4% 11.2%;
  --muted: 210 40% 96.1%;
  --muted-foreground: 215.4 16.3% 46.9%;
  /* 他の色も同様に定義されます */
}
```

これらの変数を使用することで、テーマのカスタマイズや管理が容易になり、一貫性のあるデザインシステムを構築しやすくなります。
